// import { makeStyles } from '@mui/system'

export const useStyles = () => ({
  box: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  inputLabel: {
    width: '22ch',
  },
  multiSelect: {
    width: '43.5ch',
  },
  titleLabel: {
    width: '40ch',
  },
  titleLabelWide: {
    width: '56ch',
  },
  StatusLogItemCard: {
    height: '145px',
    //     width: '100%',
    backgroundColor: '#744f44',
    //     overflow: 'hidden',
    //     boxShadow: [
    //       '0px 2px 1px -1px rgba(0, 0, 0, 0.2)',
    //       '0px 1px 1px 0px rgba(0, 0, 0, 0.14)',
    //       '0px 1px 3px 0px rgba(0, 0, 0, 0.12)',
    //     ],
    borderRadius: '4px',
    margin: '2px 10px 8px 10px',
  },
  StatusLogItemCardContent: {
    display: 'flex',
    padding: '0px 3px 0px 0px',
    top: '40px',
    alignontent: 'center',
    flexWrap: 'wrap',
    alignItems: 'center',
    color: 'whitesmoke',
  },
  logImg: {
    width: '139.95px',
    height: '144.65px',
    objectFit: 'cover',
    borderRadius: '4px',
  },
  //   logInfo: {
  //     display: 'flex',
  //     height: '70%',
  //     padding: '0px 3px 0px 6px',
  //     top: '40px',
  //     alignontent: 'center',
  //     flexWrap: 'wrap',
  //     alignItems: 'center',
  //     justifyContent: 'flex-start',
  //     color: 'whitesmoke',
  //   },
  statusButton: {
    width: '80%',
    fontWeight: '200',
    textTransform: 'uppercase',
    textAlign: 'center',
    margin: '8px',
    padding: '6px 16px',
    boxSizing: 'border-box',
    borderRadius: '4px',
  },
  wet: {
    width: '252px',
    color: 'black',
    fontWeight: '200',
    textTransform: 'uppercase',
    textAlign: 'center',
    margin: '8px',
    padding: '6px 16px',
    boxSizing: 'border-box',
    borderRadius: '4px',
    backgroundColor: '#A3D9FF',
  },
  leatherHard: {
    width: '252px',
    color: 'black',
    fontWeight: '200',
    textTransform: 'uppercase',
    textAlign: 'center',
    margin: '8px',
    padding: '6px 16px',
    boxSizing: 'border-box',
    borderRadius: '4px',
    backgroundColor: '#88A4B8',
  },
  boneDry: {
    width: '252px',
    color: 'black',
    fontWeight: '200',
    textTransform: 'uppercase',
    textAlign: 'center',
    margin: '8px',
    padding: '6px 16px',
    boxSizing: 'border-box',
    borderRadius: '4px',
    backgroundColor: '#C09F93',
  },
  bisqueFiring: {
    width: '252px',
    color: 'black',
    fontWeight: '200',
    textTransform: 'uppercase',
    textAlign: 'center',
    margin: '8px',
    padding: '6px 16px',
    boxSizing: 'border-box',
    borderRadius: '4px',
    backgroundColor: '#b98462',
  },
  bisqueFired: {
    width: '252px',
    color: 'black',
    fontWeight: '200',
    textTransform: 'uppercase',
    textAlign: 'center',
    margin: '8px',
    padding: '6px 16px',
    boxSizing: 'border-box',
    borderRadius: '4px',
    backgroundColor: '#BA6D32',
  },
  glazed: {
    width: '252px',
    color: 'black',
    fontWeight: '200',
    textTransform: 'uppercase',
    textAlign: 'center',
    margin: '8px',
    padding: '6px 16px',
    boxSizing: 'border-box',
    borderRadius: '4px',
    backgroundColor: '#6BA368',
  },
  glazeFiring: {
    color: 'black',
    fontWeight: '200',
    textTransform: 'uppercase',
    textAlign: 'center',
    margin: '8px',
    padding: '6px 16px',
    boxSizing: 'border-box',
    borderRadius: '4px',
    width: '252px',
    backgroundColor: '#AFE07E',
  },
  complete: {
    fontWeight: '200',
    textTransform: 'uppercase',
    textAlign: 'center',
    margin: '8px',
    padding: '6px 16px',
    boxSizing: 'border-box',
    borderRadius: '4px',
    width: '252px',
    backgroundColor: '#744F44',
    color: 'white',
  },
  saveButton: {
    position: 'absolute',
    color: '#e3c6a4',
    backgroundColor: '#744F44',
    right: '18px',
    bottom: '50px',
    height: '35px',
  },
  ButtonIcon: {
    color: '#e3c6a4',
  },
  MuiFab: {
    position: 'fixed',
    bottom: '1rem',
    right: '2rem',
  },
})
