exports.seed = (knex) => {
  return knex('creations').insert([
    {
      id: 1,
      clay: 1,
      shape: 5,
      status: 2,
      glaze: 4,
      weight_leather_hard: 0,
      weight_bone_dry: 0,
      weight_bisque_fired: 0,
      weight_glazed: 0,
      weight_complete: 0,
      date_created: '2020-06-15T13:45:30',
      date_completed: '2020-07-15T13:45:30',
      description: 'Creations by emily is great',
      note: 'Glaze with criss-cross pattern',
      name: 'Le Vase',
      img_leather_hard: '',
      img_bisque_fired: '',
      img_glazed: '',
      img_complete: '',
      img_gallery: '/images/vase.png'
    },
    {
      id: 2,
      clay: 2,
      shape: 2,
      status: 1,
      glaze: 2,
      weight_leather_hard: 0,
      weight_bone_dry: 0,
      weight_bisque_fired: 0,
      weight_glazed: 0,
      weight_complete: 0,
      date_created: '2020-05-24T14:45:30',
      date_completed: '2020-06-24T14:45:30',
      name: '',
      description: '',
      note: 'Glaze with criss-cross pattern',
      img_leather_hard: '',
      img_bisque_fired: '',
      img_glazed: '',
      img_complete: '',
      img_gallery: ''
    },
    {
      id: 3,
      clay: 3,
      shape: 3,
      status: 3,
      glaze: 1,
      weight_leather_hard: 0,
      weight_bone_dry: 0,
      weight_bisque_fired: 0,
      weight_glazed: 0,
      weight_complete: 0,
      date_created: '2020-05-25T14:49:30',
      date_completed: '2020-06-25T14:49:30',
      name: '',
      description: '',
      note: 'Glaze in full colour',
      img_leather_hard: '',
      img_bisque_fired: '',
      img_glazed: '',
      img_complete: '',
      img_gallery: '/images/1.png'
    },
    {
      id: 4,
      clay: 1,
      shape: 5,
      status: 4,
      glaze: 5,
      weight_leather_hard: 0,
      weight_bone_dry: 0,
      weight_bisque_fired: 0,
      weight_glazed: 0,
      weight_complete: 0,
      date_created: '2020-05-28T16:23:30',
      date_completed: '2020-07-28T16:23:30',
      name: '',
      description: '',
      note: 'Glaze in full colour',
      img_leather_hard: '',
      img_bisque_fired: '',
      img_glazed: '',
      img_complete: '',
      img_gallery: '/images/2.png'
    },
    {
      id: 5,
      clay: 1,
      shape: 2,
      status: 5,
      glaze: 8,
      weight_leather_hard: 0,
      weight_bone_dry: 0,
      weight_bisque_fired: 0,
      weight_glazed: 0,
      weight_complete: 0,
      date_created: '2020-07-12T16:11:30',
      date_completed: '2020-08-15T13:45:30',
      name: '',
      description: '',
      note: 'Glaze top-half',
      img_leather_hard: '',
      img_bisque_fired: '',
      img_glazed: '',
      img_complete: '',
      img_gallery: ''
    },
    {
      id: 6,
      clay: 3,
      shape: 7,
      status: 6,
      glaze: 6,
      weight_leather_hard: 0,
      weight_bone_dry: 0,
      weight_bisque_fired: 0,
      weight_glazed: 0,
      weight_complete: 0,
      date_created: '2020-07-20T18:56:30',
      name: '',
      date_completed: '2020-08-20T18:56:30',
      note: 'Glaze top-half and underglaze with black matte details',
      img_leather_hard: '',
      img_bisque_fired: '',
      img_glazed: '',
      img_complete: '',
      img_gallery: ''
    },
    {
      id: 7,
      clay: 1,
      shape: 1,
      status: 7,
      glaze: 3,
      weight_leather_hard: 0,
      weight_bone_dry: 0,
      weight_bisque_fired: 0,
      weight_glazed: 0,
      weight_complete: 0,
      date_created: '2020-07-21T12:34:30',
      date_completed: '2020-08-21T12:34:30',
      name: '',
      description: '',
      note: '',
      img_leather_hard: '',
      img_bisque_fired: '',
      img_glazed: '',
      img_complete: '',
      img_gallery: ''
    },
    {
      id: 8,
      clay: 3,
      shape: 6,
      status: 8,
      glaze: 7,
      weight_leather_hard: 0,
      weight_bone_dry: 0,
      weight_bisque_fired: 0,
      weight_glazed: 0,
      weight_complete: 0,
      date_created: '2020-08-03T14:12:30',
      date_completed: '2020-09-03T14:12:30',
      name: '',
      description: '',
      note: '',
      img_leather_hard: '',
      img_bisque_fired: '',
      img_glazed: '',
      img_complete: '',
      img_gallery: ''
    },
    {
      id: 9,
      clay: 2,
      shape: 4,
      status: 7,
      glaze: 4,
      weight_leather_hard: 0,
      weight_bone_dry: 0,
      weight_bisque_fired: 0,
      weight_glazed: 0,
      weight_complete: 0,
      date_created: '2020-08-10T17:22:30',
      date_completed: '2020-09-10T17:22:30',
      name: '',
      description: '',
      note: '',
      img_leather_hard: '',
      img_bisque_fired: '',
      img_glazed: '',
      img_complete: '',
      img_gallery: ''
    }
  ])
}
